"""Learn a native-script -> Latin token dictionary from the training pairs.

About 10% of Source 2/3 names are written in Devanagari, Telugu, Kannada,
Bengali, ... while Source 1 is always Latin. The vocabulary is small (~1.5k
distinct native words) and shared between train and test, so we learn a
word-translation table with IBM Model 1 (EM word alignment) over the
ground-truth pairs: each native token of a Source 2/3 name is generated by
one Latin word of the matched Source 1 name. After EM, each native token is
mapped to the Latin word with the largest expected alignment count.
Only the provided training data is used.
"""
import json
import re
from collections import defaultdict

import polars as pl
from unidecode import unidecode

from common import cache, read_ground_truth, read_source
from text_norm import _LATIN_OK

_STRIP = ".,()[]-"
_WORD = re.compile(r"[a-z0-9]+")


def native_tokens(name: str):
    return [w.strip(_STRIP) for w in name.split() if w.strip(_STRIP) and not _LATIN_OK.match(w)]


def latin_words(name: str):
    return _WORD.findall(unidecode(name).lower().replace("'", ""))


def learn(iters: int = 10, min_count: int = 2) -> dict:
    s1 = read_source("train", 1).select(pl.col("entity_id").alias("s1_id"), pl.col("business_name").alias("n1"))
    rec = pl.concat([read_source("train", 2), read_source("train", 3)]).select(
        pl.col("entity_id").alias("rec_id"), pl.col("business_name").alias("n2")
    )
    rec = rec.filter(pl.col("n2").str.contains(r"[^\x00-\x7FÀ-ɏ]"))
    pairs = read_ground_truth().join(rec, on="rec_id").join(s1, on="s1_id")

    # Deduplicate identical (native tokens, latin words) pairs and weight them.
    bag = defaultdict(int)
    for n1, n2 in zip(pairs["n1"].to_list(), pairs["n2"].to_list()):
        nt = tuple(native_tokens(n2))
        et = tuple(latin_words(n1))
        if nt and et:
            bag[(nt, et)] += 1
    data = list(bag.items())

    # IBM Model 1: t[(n, e)] = P(n | e), uniform init.
    t = defaultdict(lambda: 1.0)
    for it in range(iters):
        count = defaultdict(float)
        total = defaultdict(float)
        for (nt, et), w in data:
            for n in nt:
                z = sum(t[(n, e)] for e in et)
                for e in et:
                    c = w * t[(n, e)] / z
                    count[(n, e)] += c
                    total[e] += c
        t = defaultdict(float, {k: v / total[k[1]] for k, v in count.items()})
    # expected alignment counts from the last E-step
    best = {}
    for (n, e), c in count.items():
        if c >= min_count and (n not in best or c > best[n][1]):
            best[n] = (e, c)
    mapping = {n: e for n, (e, c) in best.items()}
    print(f"translit: {len(mapping)} native tokens mapped")
    return mapping


if __name__ == "__main__":
    m = learn()
    with open(cache("translit.json"), "w") as f:
        json.dump(m, f, ensure_ascii=False)
